import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Main from "../components/Main";
import Modal from "../components/Modal";
import Movies from "../components/Movies";
import { Movie } from "../types";

interface Props {
  main: Movie[];
}

const Home = ({ main }: Props) => {
  const showModal = useRecoilValue(modalState);
  return (
    <div className="">
      <Head>
        <title>TheCinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden">
        <Main main={main} />
        <Movies main={main} />
        {showModal && <Modal />}
      </div>
    </div>
  );
};

export default Home;
export async function getServerSideProps() {
  const response = await fetch(
    "https://api.themoviedb.org/3/discover/movie?api_key=202c50b1e2676a320151967e42b9cc3b&language=en-US&with_genres=28"
  );
  const data = await response.json();
  const { results } = data;

  return {
    props: {
      main: results,
    },
  };
}
