import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Main from "../components/Main";
import Movies from "../components/Movies";
import { Movie } from "../types";

interface Props {
  main: Movie[];
}

const Home = ({ main }: Props) => {
  // console.log(main)
  return (
    <div className="">
      <Head>
        <title>TheCinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main main={main} />
    </div>
  );
};

export default Home;
export async function getServerSideProps() {
  const response = await fetch(
    "https://api.themoviedb.org/3/discover/movie?api_key=202c50b1e2676a320151967e42b9cc3b&language=en-US&with_genres=28"
  );
  const data = await response.json();
  const { results } = data;

  return {
    props: {
      main: results,
    },
  };
}
